### ISSUE TITLE
Will you continue the project to develop?

### ISSUE THREAD

**Issue by parmanputu** [hendramchen/find-word#5]
This Find Word game is cool, I have tried on my local. But in order to add some functionality, will you continue this project?

**Comment by hendramchen** [comment]
Hi Parman, yes I will.
I will add some features on this game. The first, I will add supabase client to make easy store data without writing backend.

**Comment by parmanputu** [comment]
Cool! go ahead hendra!

**Comment by hendramchen** [comment]
Sure, Thanks!
